// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Company.Function.Models
{
    /// <summary> The TpsReport. </summary>
    public partial class TpsReport
    {
        /// <summary> Initializes a new instance of TpsReport. </summary>
        internal TpsReport()
        {
        }

        /// <summary> Initializes a new instance of TpsReport. </summary>
        /// <param name="id"> . </param>
        /// <param name="dateSubmitted"> . </param>
        /// <param name="tpsurl"> . </param>
        internal TpsReport(string id, string dateSubmitted, string tpsurl)
        {
            Id = id;
            DateSubmitted = dateSubmitted;
            Tpsurl = tpsurl;
        }

        public string Id { get; }
        public string DateSubmitted { get; }
        public string Tpsurl { get; }
    }
}
